#!/bin/bash

set -u
set -e

. '/vagrant/box-scripts/functions'

roles=$@

if [ $osfamily == 'Debian' ]
then
  code_name=$(lsb_release -c | awk '{ print $NF}')
  if [ ! -f '/root/puppetlabs.gpg' ]
  then
    wget -q http://apt.puppetlabs.com/pubkey.gpg -O /root/puppetlabs.gpg
    apt-key add /root/puppetlabs.gpg
  fi
  if [ ! -f '/etc/apt/sources.list.d/puppetlabs.list' ]
  then
    echo "deb http://apt.puppetlabs.com ${code_name} dependencies main" > /etc/apt/sources.list.d/puppetlabs.list
    apt-get update
  fi
  PackageInstall puppet-common
#  PackageInstall git
  puppet agent --enable
elif [ $osfamily == 'RedHat' ]
then
# Add the Puppet repositories
  if [ ! -f '/etc/yum.repos.d/puppet.repo' ]
  then
    echo -e "[puppet-products]\nname=puppet-products\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/products/\$basearch\ngpgcheck=0\nenabled=1" > /etc/yum.repos.d/puppet.repo
    echo -e "[puppet-dependencies]\nname=puppet-dependencies\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/dependencies/\$basearch\ngpgcheck=0\nenabled=1" >> /etc/yum.repos.d/puppet.repo
  fi
# Install some things
  PackageInstall puppet
else
  Fail "Unsupported OS"  
fi

# Puppet should be installed now, so facter can be used
fqdn=$(facter fqdn)

# Verify that the "puppet" entry is in /etc/hosts, until DNS is used
set +e
grep -q ^10\.1\.1\.4 /etc/hosts
result=$?
set -e
if [ $result -ne 0 ]
then
  echo -e "10.1.1.4\tpuppet" >> /etc/hosts
fi

# Verify that $fqdn is in /etc/hosts.  This may happen if DHCP appends a
# domain to the Vagrant hostname, or if DNS is using funky wildcards
set +e
grep -q -w "$fqdn" /etc/hosts
result=$?
set -e
if [ $result -ne 0 ]
then
  sed -i "s/^\(127.0.0.1\)\s*\(.*\)/\1\t$fqdn\ \2/" /etc/hosts
fi
set -e

PuppetConfigSet environment "$puppet_environment"

# Include any subsequent scripts that may have been passed
for role in ${roles[@]}
do
  echo "Including $role role"
  sh /vagrant/box-scripts/${role} $0
done

# Finally, run Puppet
# It may be running already, or it may return non-zero.  Vagrant shouldn't care,
# so error checking's removed
set +e
puppet agent -t
set -e
